name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Install dependencies and test
        run: pnpm install-test --frozen-lockfile
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: ${{ steps.publish.outputs.type }}
        run: |
          echo "Published version: ${{ steps.publish.outputs.version }}"
      - name: Deploy
        run: pnpm run deploy
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          target-folder: public
          single-commit: true
